development:
  dialect: "postgres"
  database: "development"
  host: "postmurumserver_postgres_1"
  port: "5432"
  user: "postgres"
  password: "demo"

production:
  dialect: "postgres"
  url: {{ env "DATABASE_URL" }}